name: ublue akmods 40
on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 40